net/cnxk: fix compilation issue for gcc12
resolve compilation error caused due to gcc 12 version
error: storing the address of local variable message in *error.message

Fixes: 26b034f78ca7 ("net/cnxk: support to validate meter policy")

Cc: stable@dpdk.org

Signed-off-by: Rakesh Kudurumalla <rkudurumalla@marvell.com>
Change-Id: Ia4cf18471ae33691c34229ab537f208389e0f780
Reviewed-on: https://sj1git1.cavium.com/c/IP/SW/dataplane/dpdk/+/71434
Reviewed-by: Jerin Jacob Kollanukkaran <jerinj@marvell.com>
Tested-by: Jerin Jacob Kollanukkaran <jerinj@marvell.com>